[dev]
framework = "#custom"
command = "npm start"
targetPort = 3001

[build]
command = "npm run build && mkdir build && cp public/* build && cp -r dist build/dist"
publish = "build"
functions = "src/functions"

[[redirects]]
from = "/api/*"
to = "/.netlify/functions/:splat"
status = 200

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
force = false
